/************************************************************\
**	Copyright (c) 2012-2025 Anlogic Inc.
**	All Right Reserved.
\************************************************************/
/************************************************************\
**	Build time: Jul 07 2025 14:58:10
**	TD version	:	6.1.155545
************************************************************/
`timescale 1ps/1ps
module ddr2
(
  input                         ref_clk,
  input                         sys_rst_n,
  input                         apb_pclk,
  input                         apb_prst_n,
  input                         apb_psel,
  input                         apb_penable,
  input                         apb_pwrite,
  input   [27:0]                apb_paddr,
  input   [31:0]                apb_pwdata,
  input   [24:0]                paxi_awaddr,
  input                         paxi_awvalid,
  input   [127:0]               paxi_wdata,
  input   [15:0]                paxi_wstrb,
  input                         paxi_wvalid,
  input                         paxi_wlast,
  input   [24:0]                paxi_araddr,
  input                         paxi_arvalid,
  input                         paxi_rready,
  output                        apb_pready,
  output  [31:0]                apb_prdata,
  output                        dhi_clk,
  output                        cfg_clk,
  output                        cfg_rst_n,
  output                        ddrphy_rst_n,
  output                        ddrphy_rdy,
  output                        paxi_awready,
  output                        paxi_wready,
  output                        paxi_arready,
  output  [127:0]               paxi_rdata,
  output                        paxi_rlast,
  output                        paxi_rvalid,
  output  [0:0]                 ddr_cke,
  output  [0:0]                 ddr_odt,
  output  [0:0]                 ddr_cs_n,
  output  [1:0]                 ddr_ba,
  output  [12:0]                ddr_addr,
  output  [0:0]                 ddr_ck_p,
  output  [0:0]                 ddr_ck_n,
  output  [0:0]                 ddr_ras_n,
  output  [0:0]                 ddr_cas_n,
  output  [0:0]                 ddr_we_n,
  inout   [15:0]                ddr_dq,
  inout   [1:0]                 ddr_dqs_p,
  inout   [1:0]                 ddr_dqs_n,
  inout   [1:0]                 ddr_dm
);

  ph1p_ddrmc_wrapper_63f4ac254419
  #(
      .tCK(1876),
      .BK_NUM(2),
      .AC_NUM(4),
      .DX_NUM(2),
      .CK_WIDTH(1),
      .CS_WIDTH(1),
      .CKE_WIDTH(1),
      .ODT_WIDTH(1),
      .BG_WIDTH(0),
      .BA_WIDTH(2),
      .ROW_WIDTH(13),
      .COL_WIDTH(10),
      .ADR_WIDTH(13),
      .HOST_AC_DRV("75"),
      .HOST_DX_DRV("75"),
      .HOST_DX_ODT("75"),
      .DRAM_DRV("0"),
      .DRAM_ODT("75"),
      .CWL(6),
      .CL(7),
      .PLL0_REFCLK_FREQ(25.0),
      .PLL0_REFCLK_DIV(2),
      .PLL0_FBKCLK_DIV(85),
      .PLL0_FRAC("DISABLE"),
      .PLL0_FRAC_SDM(0),
      .PLL0_CLK2_DIV(2),
      .PLL0_CLK3_DIV(21),
      .PLL1_REFCLK_FREQ(132.8),
      .PLL1_REFCLK_DIV(2),
      .PLL1_CLK0_DIV(7),
      .MC_ECC("OFF"),
      .MC_ADDR_MAP("ROW_COL_BANK"),
      .MC_REORDER("NORMAL"),
      .MC_ADDR_WIDTH(25),
      .MC_DATA_WIDTH(128),
      .MC_MASK_WIDTH(16)
  )ph1p_ddrmc_wrapper
  (
      .ref_clk(ref_clk),
      .sys_rst_n(sys_rst_n),
      .apb_pclk(apb_pclk),
      .apb_prst_n(apb_prst_n),
      .apb_pready(apb_pready),
      .apb_psel(apb_psel),
      .apb_penable(apb_penable),
      .apb_pwrite(apb_pwrite),
      .apb_paddr(apb_paddr),
      .apb_pwdata(apb_pwdata),
      .apb_prdata(apb_prdata),
      .dhi_clk(dhi_clk),
      .cfg_clk(cfg_clk),
      .cfg_rst_n(cfg_rst_n),
      .ddrphy_rst_n(ddrphy_rst_n),
      .ddrphy_rdy(ddrphy_rdy),
      .paxi_awaddr(paxi_awaddr),
      .paxi_awvalid(paxi_awvalid),
      .paxi_awready(paxi_awready),
      .paxi_wdata(paxi_wdata),
      .paxi_wstrb(paxi_wstrb),
      .paxi_wvalid(paxi_wvalid),
      .paxi_wlast(paxi_wlast),
      .paxi_wready(paxi_wready),
      .paxi_araddr(paxi_araddr),
      .paxi_arvalid(paxi_arvalid),
      .paxi_arready(paxi_arready),
      .paxi_rdata(paxi_rdata),
      .paxi_rlast(paxi_rlast),
      .paxi_rvalid(paxi_rvalid),
      .paxi_rready(paxi_rready),
      .ddr_ck_p(ddr_ck_p),
      .ddr_ck_n(ddr_ck_n),
      .ddr_cke(ddr_cke),
      .ddr_odt(ddr_odt),
      .ddr_cs_n(ddr_cs_n),
      .ddr_ras_n(ddr_ras_n),
      .ddr_cas_n(ddr_cas_n),
      .ddr_we_n(ddr_we_n),
      .ddr_ba(ddr_ba),
      .ddr_addr(ddr_addr),
      .ddr_dqs_p(ddr_dqs_p),
      .ddr_dqs_n(ddr_dqs_n),
      .ddr_dq(ddr_dq),
      .ddr_dm(ddr_dm)
  );
endmodule
